# prettier-ignore

version: "3.9"

networks:
  web:
    name: web
    external: false
  internal:
    name: internal
    external: false

services:
  traefik:
    image: traefik
    profiles: ["server", "traefik"]
    restart: unless-stopped
    command:
      - --api.insecure=true 
      - --providers.docker=true 
      - --providers.docker.exposedbydefault=false 
      - --log.level=${TRAEFIK_LOG}
      - --entrypoints.http.address=:80 
      - --entrypoints.https.address=:443
      - --certificatesresolvers.${TRAEFIK_ACME_PROVIDER}.acme.tlschallenge=true
      - --certificatesresolvers.${TRAEFIK_ACME_PROVIDER}.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.${TRAEFIK_ACME_PROVIDER}.acme.storage=acme.json
    networks:
      - internal
      - web
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    build: .
    profiles: ["server", "api"]
    restart: unless-stopped
    labels:
      - traefik.enable=true
      # Default route over HTTPS
      - traefik.http.routers.ordit.rule=Host(`${API_DOMAIN}`)
      - traefik.http.routers.ordit.entrypoints=https
      - traefik.http.routers.ordit.tls.certresolver=${TRAEFIK_ACME_PROVIDER}
      # HTTP to HTTPS
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.ordit-redirect.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.ordit-redirect.entrypoints=http
      - traefik.http.routers.ordit-redirect.middlewares=redirect-to-https
    env_file:
      - .env
    networks:
      - internal
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      replicas: ${API_REPLICAS}
      restart_policy:
        max_attempts: 3
        condition: on-failure
    command: npm start

  bitcoin:
    image: ruimarinho/bitcoin-core
    profiles: ["local", "bitcoin"]
    restart: unless-stopped
    labels:
      - traefik.enable=false
    ports:
      - ${RPC_PORT}:${RPC_PORT} # regtest:18443 testnet:18332 mainnet:8332
    volumes:
      - ./.data/bitcoin:/home/bitcoin/.bitcoin
    networks:
      - internal
    command:
      -printtoconsole
      -txindex=1
      -${NETWORK}=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=bitcoin
      -rpcpassword=bitcoin
      -blocknotify='curl ${RPC_NOTIFY}/hooks/bitcoin?block=%s'

  mongodb:
    image: mongo:latest
    profiles: ["local", "db", "mongodb"]
    restart: unless-stopped
    labels:
      - traefik.enable=false
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - internal
    volumes:
      - ./.data/mongodb:/data/db
